export const products = [
  {
    id: "black-08-tee",
    name: "08 黑色短袖",
    note: "胸前小标 / 背后红色印花",
    description: "重磅棉质街头短袖，胸前做旧红色小标，背后大号 08 印花，适合日常出发。",
    colors: ["黑色", "水洗红"],
    front: "tee-black-front.png",
    back: "tee-black-back.png",
  },
  {
    id: "white-08-tee",
    name: "08 白色短袖",
    note: "灰色前标 / 蓝色背印",
    description: "暖白色短袖，正面克制 08 标记，背后蓝色图案，干净但有力量。",
    colors: ["白色", "蓝色印花"],
    front: "tee-white-front.png",
    back: "tee-white-back.png",
  },
  {
    id: "outer-layer",
    name: "外套预留款",
    note: "等待图片",
    description: "预留给下一件外套的位置，图片与最终信息会在之后补充。",
    colors: ["水泥灰", "黑色"],
    slot: "单品预留 03",
  },
  {
    id: "accessory",
    name: "配件预留款",
    note: "等待图片",
    description: "预留给帽子或配件的位置，用来延展 PANSK 的日常穿搭系统。",
    colors: ["黑色"],
    slot: "单品预留 04",
    dark: true,
  },
  {
    id: "video-loop",
    name: "动态影像预留",
    note: "5-10 秒上身动态",
    description: "预留给短视频上身片段的位置，暂不作为可购买商品。",
    colors: ["动态"],
    slot: "影像预留 01",
  },
];

export const showcaseProducts = [
  {
    id: "mesh-08-jersey",
    name: "08 黑色网眼球衣",
    note: "黑色网眼运动上衣",
    description: "黑色网眼球衣，大号 08 数字与袖章细节，短宽廓形带来街头运动感。",
    colors: ["黑色", "红 / 白"],
    front: "showcase-mesh-08-default.jpg",
    back: "showcase-mesh-08-hover.jpg",
    imageFit: "cover",
    hoverFit: "cover",
  },
  {
    id: "white-01-jersey",
    name: "01 白色球衣",
    note: "白色数字球衣",
    description: "白色短袖球衣，正面大号 01 图形，红黑撞色让日常更有记忆点。",
    colors: ["白色", "黑 / 红"],
    front: "showcase-white-01-default.jpg",
    back: "showcase-white-01-hover.jpg",
    imageFit: "cover",
    hoverFit: "cover",
  },
  {
    id: "rebellion-tee",
    name: "反叛图案黑色短袖",
    note: "图案棉质短袖",
    description: "水洗黑色图案短袖，密集拼贴印花，像把少年的态度穿在身上。",
    colors: ["水洗黑"],
    front: "showcase-rebellion-tee-default.png",
    back: "showcase-rebellion-tee-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "wide-denim",
    name: "蓝色宽松水洗牛仔",
    note: "宽松水洗丹宁",
    description: "宽腿水洗牛仔裤，垂坠松弛，蓝色刮痕水洗适合走很远的路。",
    colors: ["水洗蓝"],
    front: "showcase-denim-default.png",
    back: "showcase-denim-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "grey-cardigan",
    name: "灰色针织开衫",
    note: "柔软灰色针织层次",
    description: "灰色纽扣开衫，带 PANSK 小字标记，柔软宽松，适合温柔地出门。",
    colors: ["灰色"],
    front: "showcase-cardigan-default.png",
    back: "showcase-cardigan-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "blue-sweatpants",
    name: "蓝色宽腿卫裤",
    note: "蓝色宽松运动长裤",
    description: "蓝色宽腿卫裤，白色图案标记，松弛运动廓形，陪你去见今天。",
    colors: ["蓝色", "白色印花"],
    front: "showcase-blue-pants-default.png",
    back: "showcase-blue-pants-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
];

export const newProducts = [
  {
    id: "pansk-punk-cat-tee-white",
    name: "PANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤",
    note: "短袖 / 白色印花 T 恤",
    description: "白色圆领短袖 T 恤，正面朋克猫图案直喷印花，宽松春夏基础版型。",
    colors: ["白色"],
    front: "PANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤.png",
    back: "PANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "ansk-punk-cat-tee-white",
    name: "ANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤",
    note: "长袖 / 白色印花 T 恤",
    description: "白色长袖圆领 T 恤，正面朋克猫图案直喷印花，宽松日常版型。",
    colors: ["白色"],
    front: "ANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤.png",
    back: "ANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "light-blue-denim-jacket",
    name: "PANSK高盎司浅蓝水洗破坏牛仔夹克外套短宽版型",
    note: "外套 / 浅蓝水洗牛仔夹克",
    description: "高盎司浅蓝水洗牛仔夹克，短宽版型，领口拼接复古灯芯绒质感。",
    colors: ["浅蓝", "棕色领口"],
    front: "PANSK高盎司浅蓝水洗破坏牛仔夹克外套短宽版型.png",
    back: "PANSK高盎司浅蓝水洗破坏牛仔夹克外套短宽版型-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "salt-wash-boxy-jacket",
    name: "PANSK【水洗炒盐夹克】做旧短款收腰底特律Boxy版型Cleanfit",
    note: "外套 / 水洗炒盐夹克",
    description: "做旧短款收腰底特律夹克，Boxy 版型，Cleanfit 日常叠穿外套。",
    colors: ["水洗青", "棕色领口"],
    front: "PANSK【水洗炒盐夹克】做旧短款收腰底特律Boxy版型Cleanfit.png",
    back: "PANSK【水洗炒盐夹克】做旧短款收腰底特律Boxy版型Cleanfit-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "indigo-14oz-whisker-jeans",
    name: "PANSK靛蓝14oz复古丹宁本色靛光牛仔立体水洗猫须直筒微喇长裤",
    note: "牛仔裤 / 靛蓝 14oz 猫须水洗",
    description: "靛蓝 14oz 复古丹宁长裤，立体水洗猫须效果，直筒微喇裤型。",
    colors: ["靛蓝水洗"],
    front: "PANSK靛蓝14oz复古丹宁本色靛光牛仔立体水洗猫须直筒微喇长裤.png",
    back: "PANSK靛蓝14oz复古丹宁本色靛光牛仔立体水洗猫须直筒微喇长裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "plain-12oz-denim-jeans",
    name: "PANSK丹宁风牛仔裤12oz素版直筒基础百搭休闲长裤子男",
    note: "牛仔裤 / 12oz 素版直筒",
    description: "12oz 丹宁风素版牛仔裤，直筒基础百搭版型，适合日常休闲穿着。",
    colors: ["丹宁蓝"],
    front: "PANSK丹宁风牛仔裤12oz素版直筒基础百搭休闲长裤子男.png",
    back: "PANSK丹宁风牛仔裤12oz素版直筒基础百搭休闲长裤子男-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "coffee-wash-denim-jeans",
    name: "PANSK【咖啡水洗牛】13盎司阿苏特染直筒阔腿A字牛仔裤",
    note: "牛仔裤 / 咖啡水洗 13oz",
    description: "咖啡水洗 13 盎司牛仔裤，直筒阔腿 A 字裤型，复古阿苏特染色质感。",
    colors: ["咖啡水洗"],
    front: "PANSK【咖啡水洗牛】13盎司阿苏特染直筒阔腿A字牛仔裤.png",
    back: "PANSK【咖啡水洗牛】13盎司阿苏特染直筒阔腿A字牛仔裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "branch-maple-camo-cargo",
    name: "PANSK【树枝枫叶】数码直喷迷彩设计感直筒多口袋工装裤",
    note: "工装裤 / 树枝枫叶迷彩",
    description: "树枝枫叶数码直喷迷彩图案，直筒多口袋工装裤，设计感户外街头版型。",
    colors: ["迷彩"],
    front: "PANSK【树枝枫叶】数码直喷迷彩设计感直筒多口袋工装裤.png",
    back: "PANSK【树枝枫叶】数码直喷迷彩设计感直筒多口袋工装裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "five-button-kanglong-raw-denim",
    name: "PANSK【五连扣康龙原牛】手缝针黑羽棉康龙宽松直筒牛仔裤14oz",
    note: "牛仔裤 / 黑色 14oz 五连扣",
    description: "14oz 黑色康龙原牛牛仔裤，五连扣门襟，手缝针黑羽棉细节，宽松直筒版型。",
    colors: ["黑色原牛"],
    front: "PANSK【五连扣康龙原牛】手缝针黑羽棉康龙宽松直筒牛仔裤14oz.png",
    back: "PANSK【五连扣康龙原牛】手缝针黑羽棉康龙宽松直筒牛仔裤14oz-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "suede-ear-black-raw-denim",
    name: "PANSK【麂皮翻耳】巴恩风直筒修身未脱浆黑色原牛牛仔裤长裤",
    note: "牛仔裤 / 麂皮翻耳黑色原牛",
    description: "黑色未脱浆原牛牛仔裤，麂皮翻耳口袋细节，巴恩风直筒修身长裤版型。",
    colors: ["黑色原牛", "麂皮细节"],
    front: "PANSK【麂皮翻耳】巴恩风直筒修身未脱浆黑色原牛牛仔裤长裤.png",
    back: "PANSK【麂皮翻耳】巴恩风直筒修身未脱浆黑色原牛牛仔裤长裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "non-fade-2021m-raw-denim",
    name: "PANSK【不褪色原牛】2021M简约休闲cleanfit原色牛仔裤",
    note: "牛仔裤 / 2021M 原色不褪色",
    description: "2021M 简约休闲 Cleanfit 原色牛仔裤，不褪色原牛质感，日常直筒版型。",
    colors: ["原色靛蓝"],
    front: "PANSK【不褪色原牛】2021M简约休闲cleanfit原色牛仔裤.png",
    back: "PANSK【不褪色原牛】2021M简约休闲cleanfit原色牛仔裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "deep-blue-14oz-honeycomb-jeans",
    name: "PANSK 14oz复古深蓝色重工水洗'蜂窝‘猫须2021M宽松直筒牛仔裤",
    note: "牛仔裤 / 14oz 深蓝蜂窝猫须",
    description: "14oz 复古深蓝重工水洗牛仔裤，蜂窝与猫须水洗效果，2021M 宽松直筒版型。",
    colors: ["深蓝水洗"],
    front: "PANSK 14oz复古深蓝色重工水洗'蜂窝‘猫须2021M宽松直筒牛仔裤.png",
    back: "PANSK 14oz复古深蓝色重工水洗'蜂窝‘猫须2021M宽松直筒牛仔裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
];

const byId = new Map([...showcaseProducts, ...newProducts].map((product) => [product.id, product]));
const pickProducts = (ids) => ids.map((id) => byId.get(id)).filter(Boolean);

export const productGroups = [
  {
    id: "tops",
    label: "上衣",
    title: "上装",
    note: "短袖 / 长袖 / 外套",
    categories: [
      {
        id: "short-sleeve",
        label: "短袖",
        title: "短袖",
        products: pickProducts(["mesh-08-jersey", "white-01-jersey", "rebellion-tee", "pansk-punk-cat-tee-white"]),
      },
      {
        id: "long-sleeve",
        label: "长袖",
        title: "长袖",
        products: pickProducts(["ansk-punk-cat-tee-white"]),
      },
      {
        id: "outerwear",
        label: "外套",
        title: "外套",
        products: pickProducts(["grey-cardigan", "light-blue-denim-jacket", "salt-wash-boxy-jacket"]),
      },
    ],
  },
  {
    id: "pants",
    label: "长裤",
    title: "长裤",
    note: "牛仔 / 休闲直筒 / 工装",
    categories: [
      {
        id: "denim",
        label: "牛仔裤",
        title: "丹宁",
        products: pickProducts([
          "wide-denim",
          "indigo-14oz-whisker-jeans",
          "plain-12oz-denim-jeans",
          "coffee-wash-denim-jeans",
          "five-button-kanglong-raw-denim",
          "suede-ear-black-raw-denim",
          "non-fade-2021m-raw-denim",
          "deep-blue-14oz-honeycomb-jeans",
        ]),
      },
      {
        id: "work-pants",
        label: "工装 / 休闲长裤",
        title: "工装长裤",
        products: pickProducts(["blue-sweatpants", "branch-maple-camo-cargo"]),
      },
    ],
  },
];

export const categorizedProducts = productGroups.flatMap((group) =>
  group.categories.flatMap((category) => category.products)
);

const placeholderProducts = Array.from({ length: 19 }, (_, index) => {
  const number = String(index + 7).padStart(2, "0");
  return {
    id: `reserved-product-${number}`,
    name: `待上新单品 ${number}`,
    note: "等待图片",
    description: "为即将到来的 PANSK 单品预留位置，图片与最终信息会在之后补充。",
    colors: ["待定"],
    slot: `单品预留 ${number}`,
  };
});

export const shopProducts = [...categorizedProducts, ...products.slice(0, 2), ...placeholderProducts].slice(0, 25);


