export const products = [
  {
    id: "black-08-tee",
    name: "08 Tee / Black",
    note: "Front mark, red back print",
    description: "Heavy cotton streetwear tee with a small faded red chest mark and a distressed oversized 08 back print.",
    colors: ["Black", "Washed Red"],
    front: "tee-black-front.png",
    back: "tee-black-back.png",
  },
  {
    id: "white-08-tee",
    name: "08 Tee / White",
    note: "Grey front mark, blue back print",
    description: "Warm white tee with a restrained front 08 and a blue hope graphic across the back.",
    colors: ["White", "Blue Print"],
    front: "tee-white-front.png",
    back: "tee-white-back.png",
  },
  {
    id: "outer-layer",
    name: "Outer Layer",
    note: "Awaiting image",
    description: "Reserved slot for the first outerwear piece. Image and final details will be added later.",
    colors: ["Concrete", "Black"],
    slot: "Product slot 03",
  },
  {
    id: "accessory",
    name: "Accessory",
    note: "Awaiting image",
    description: "Reserved slot for an accessory or cap that can extend the Drop 08 system.",
    colors: ["Black"],
    slot: "Product slot 04",
    dark: true,
  },
  {
    id: "video-loop",
    name: "Video Loop",
    note: "5-10s model motion",
    description: "Reserved media slot for a short product motion loop. Not a purchasable item yet.",
    colors: ["Motion"],
    slot: "Motion slot 01",
  },
];

export const showcaseProducts = [
  {
    id: "mesh-08-jersey",
    name: "08 Mesh Jersey / Black",
    note: "Black mesh football top",
    description: "Black mesh jersey with oversized 08 numbering, sleeve patches, and a cropped streetwear fit.",
    colors: ["Black", "Red / White"],
    front: "showcase-mesh-08-default.jpg",
    back: "showcase-mesh-08-hover.jpg",
    imageFit: "cover",
    hoverFit: "cover",
  },
  {
    id: "white-01-jersey",
    name: "01 Jersey / White",
    note: "White number jersey",
    description: "White short sleeve jersey with oversized 01 graphics and contrast red-black numbering.",
    colors: ["White", "Black / Red"],
    front: "showcase-white-01-default.jpg",
    back: "showcase-white-01-hover.jpg",
    imageFit: "cover",
    hoverFit: "cover",
  },
  {
    id: "rebellion-tee",
    name: "Rebellion Tee / Black",
    note: "Graphic cotton tee",
    description: "Washed black graphic tee with a dense PANSK rebellion collage print.",
    colors: ["Washed Black"],
    front: "showcase-rebellion-tee-default.png",
    back: "showcase-rebellion-tee-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "wide-denim",
    name: "Wide Denim / Blue",
    note: "Loose washed denim",
    description: "Wide-leg washed denim with a relaxed drape and scratched blue finish.",
    colors: ["Washed Blue"],
    front: "showcase-denim-default.png",
    back: "showcase-denim-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "grey-cardigan",
    name: "Script Cardigan / Grey",
    note: "Soft grey knit layer",
    description: "Grey button cardigan with a small PANSK script mark and soft oversized volume.",
    colors: ["Grey"],
    front: "showcase-cardigan-default.png",
    back: "showcase-cardigan-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "blue-sweatpants",
    name: "God Based Pants / Blue",
    note: "Blue wide sweatpant",
    description: "Blue wide-leg sweatpant with white graphic marks and a relaxed sports silhouette.",
    colors: ["Blue", "White Print"],
    front: "showcase-blue-pants-default.png",
    back: "showcase-blue-pants-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
];

export const newProducts = [
  {
    id: "pansk-punk-cat-tee-white",
    name: "PANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤",
    note: "短袖 / 白色印花 T 恤",
    description: "白色圆领短袖 T 恤，正面朋克猫图案直喷印花，宽松春夏基础版型。",
    colors: ["White"],
    front: "PANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤.png",
    back: "PANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "ansk-punk-cat-tee-white",
    name: "ANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤",
    note: "长袖 / 白色印花 T 恤",
    description: "白色长袖圆领 T 恤，正面朋克猫图案直喷印花，宽松日常版型。",
    colors: ["White"],
    front: "ANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤.png",
    back: "ANSK朋克猫短袖直喷印花宽松春夏索罗娜白色圆领百搭薄款T恤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "light-blue-denim-jacket",
    name: "PANSK高盎司浅蓝水洗破坏牛仔夹克外套短宽版型",
    note: "外套 / 浅蓝水洗牛仔夹克",
    description: "高盎司浅蓝水洗牛仔夹克，短宽版型，领口拼接复古灯芯绒质感。",
    colors: ["Light Blue", "Brown Collar"],
    front: "PANSK高盎司浅蓝水洗破坏牛仔夹克外套短宽版型.png",
    back: "PANSK高盎司浅蓝水洗破坏牛仔夹克外套短宽版型-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "salt-wash-boxy-jacket",
    name: "PANSK【水洗炒盐夹克】做旧短款收腰底特律Boxy版型Cleanfit",
    note: "外套 / 水洗炒盐夹克",
    description: "做旧短款收腰底特律夹克，Boxy 版型，Cleanfit 日常叠穿外套。",
    colors: ["Aqua Wash", "Brown Collar"],
    front: "PANSK【水洗炒盐夹克】做旧短款收腰底特律Boxy版型Cleanfit.png",
    back: "PANSK【水洗炒盐夹克】做旧短款收腰底特律Boxy版型Cleanfit-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "indigo-14oz-whisker-jeans",
    name: "PANSK靛蓝14oz复古丹宁本色靛光牛仔立体水洗猫须直筒微喇长裤",
    note: "牛仔裤 / 靛蓝 14oz 猫须水洗",
    description: "靛蓝 14oz 复古丹宁长裤，立体水洗猫须效果，直筒微喇裤型。",
    colors: ["Indigo Wash"],
    front: "PANSK靛蓝14oz复古丹宁本色靛光牛仔立体水洗猫须直筒微喇长裤.png",
    back: "PANSK靛蓝14oz复古丹宁本色靛光牛仔立体水洗猫须直筒微喇长裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "plain-12oz-denim-jeans",
    name: "PANSK丹宁风牛仔裤12oz素版直筒基础百搭休闲长裤子男",
    note: "牛仔裤 / 12oz 素版直筒",
    description: "12oz 丹宁风素版牛仔裤，直筒基础百搭版型，适合日常休闲穿着。",
    colors: ["Denim Blue"],
    front: "PANSK丹宁风牛仔裤12oz素版直筒基础百搭休闲长裤子男.png",
    back: "PANSK丹宁风牛仔裤12oz素版直筒基础百搭休闲长裤子男-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "coffee-wash-denim-jeans",
    name: "PANSK【咖啡水洗牛】13盎司阿苏特染直筒阔腿A字牛仔裤",
    note: "牛仔裤 / 咖啡水洗 13oz",
    description: "咖啡水洗 13 盎司牛仔裤，直筒阔腿 A 字裤型，复古阿苏特染色质感。",
    colors: ["Coffee Wash"],
    front: "PANSK【咖啡水洗牛】13盎司阿苏特染直筒阔腿A字牛仔裤.png",
    back: "PANSK【咖啡水洗牛】13盎司阿苏特染直筒阔腿A字牛仔裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "branch-maple-camo-cargo",
    name: "PANSK【树枝枫叶】数码直喷迷彩设计感直筒多口袋工装裤",
    note: "工装裤 / 树枝枫叶迷彩",
    description: "树枝枫叶数码直喷迷彩图案，直筒多口袋工装裤，设计感户外街头版型。",
    colors: ["Camo"],
    front: "PANSK【树枝枫叶】数码直喷迷彩设计感直筒多口袋工装裤.png",
    back: "PANSK【树枝枫叶】数码直喷迷彩设计感直筒多口袋工装裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "five-button-kanglong-raw-denim",
    name: "PANSK【五连扣康龙原牛】手缝针黑羽棉康龙宽松直筒牛仔裤14oz",
    note: "牛仔裤 / 黑色 14oz 五连扣",
    description: "14oz 黑色康龙原牛牛仔裤，五连扣门襟，手缝针黑羽棉细节，宽松直筒版型。",
    colors: ["Black Raw Denim"],
    front: "PANSK【五连扣康龙原牛】手缝针黑羽棉康龙宽松直筒牛仔裤14oz.png",
    back: "PANSK【五连扣康龙原牛】手缝针黑羽棉康龙宽松直筒牛仔裤14oz-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "suede-ear-black-raw-denim",
    name: "PANSK【麂皮翻耳】巴恩风直筒修身未脱浆黑色原牛牛仔裤长裤",
    note: "牛仔裤 / 麂皮翻耳黑色原牛",
    description: "黑色未脱浆原牛牛仔裤，麂皮翻耳口袋细节，巴恩风直筒修身长裤版型。",
    colors: ["Black Raw Denim", "Suede Detail"],
    front: "PANSK【麂皮翻耳】巴恩风直筒修身未脱浆黑色原牛牛仔裤长裤.png",
    back: "PANSK【麂皮翻耳】巴恩风直筒修身未脱浆黑色原牛牛仔裤长裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "non-fade-2021m-raw-denim",
    name: "PANSK【不褪色原牛】2021M简约休闲cleanfit原色牛仔裤",
    note: "牛仔裤 / 2021M 原色不褪色",
    description: "2021M 简约休闲 Cleanfit 原色牛仔裤，不褪色原牛质感，日常直筒版型。",
    colors: ["Raw Indigo"],
    front: "PANSK【不褪色原牛】2021M简约休闲cleanfit原色牛仔裤.png",
    back: "PANSK【不褪色原牛】2021M简约休闲cleanfit原色牛仔裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
  {
    id: "deep-blue-14oz-honeycomb-jeans",
    name: "PANSK 14oz复古深蓝色重工水洗'蜂窝‘猫须2021M宽松直筒牛仔裤",
    note: "牛仔裤 / 14oz 深蓝蜂窝猫须",
    description: "14oz 复古深蓝重工水洗牛仔裤，蜂窝与猫须水洗效果，2021M 宽松直筒版型。",
    colors: ["Deep Blue Wash"],
    front: "PANSK 14oz复古深蓝色重工水洗'蜂窝‘猫须2021M宽松直筒牛仔裤.png",
    back: "PANSK 14oz复古深蓝色重工水洗'蜂窝‘猫须2021M宽松直筒牛仔裤-hover.png",
    imageFit: "contain",
    hoverFit: "cover",
  },
];

const byId = new Map([...showcaseProducts, ...newProducts].map((product) => [product.id, product]));
const pickProducts = (ids) => ids.map((id) => byId.get(id)).filter(Boolean);

export const productGroups = [
  {
    id: "tops",
    label: "上衣",
    title: "Upper Garments",
    note: "短袖 / 长袖 / 外套",
    categories: [
      {
        id: "short-sleeve",
        label: "短袖",
        title: "Short Sleeve",
        products: pickProducts(["mesh-08-jersey", "white-01-jersey", "rebellion-tee", "pansk-punk-cat-tee-white"]),
      },
      {
        id: "long-sleeve",
        label: "长袖",
        title: "Long Sleeve",
        products: pickProducts(["ansk-punk-cat-tee-white"]),
      },
      {
        id: "outerwear",
        label: "外套",
        title: "Outerwear",
        products: pickProducts(["grey-cardigan", "light-blue-denim-jacket", "salt-wash-boxy-jacket"]),
      },
    ],
  },
  {
    id: "pants",
    label: "长裤",
    title: "Pants",
    note: "牛仔 / 休闲直筒 / 工装",
    categories: [
      {
        id: "denim",
        label: "牛仔裤",
        title: "Denim",
        products: pickProducts([
          "wide-denim",
          "indigo-14oz-whisker-jeans",
          "plain-12oz-denim-jeans",
          "coffee-wash-denim-jeans",
          "five-button-kanglong-raw-denim",
          "suede-ear-black-raw-denim",
          "non-fade-2021m-raw-denim",
          "deep-blue-14oz-honeycomb-jeans",
        ]),
      },
      {
        id: "work-pants",
        label: "工装 / 休闲长裤",
        title: "Work Pants",
        products: pickProducts(["blue-sweatpants", "branch-maple-camo-cargo"]),
      },
    ],
  },
];

export const categorizedProducts = productGroups.flatMap((group) =>
  group.categories.flatMap((category) => category.products)
);

const placeholderProducts = Array.from({ length: 19 }, (_, index) => {
  const number = String(index + 7).padStart(2, "0");
  return {
    id: `reserved-product-${number}`,
    name: `Reserved Product ${number}`,
    note: "Awaiting image",
    description: "Reserved slot for an upcoming PANSK product. Image and final product details will be added later.",
    colors: ["TBD"],
    slot: `Product slot ${number}`,
  };
});

export const shopProducts = [...categorizedProducts, ...products.slice(0, 2), ...placeholderProducts].slice(0, 25);


